name: CRE
favicon: null
layout_spectrum: 0.9545216071419418
typography_spectrum: 0.0389661171939224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.10345456376671791
  lightness: 0.1577637647278607
  saturation: 0.7886555036529899
  rhythmicContrast: 0.05479752249084413
purpose: []
